Feature/boo 195 usuario miembro en busqueda de foros
BookLinkLab/booklink-back pull request #32
Opened 2023-09-16 19:02 UTC by Joafac4

2023-09-17 13:20 UTC, TomasBruno1 requested changes
Hay algunas cosas para mejorar

2023-09-17 13:20 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/service/impl/ForumServiceImpl.java
> +            throw new UserNotAdminException("El usuario no es el administrador del foro %s".formatted(getForumEntityById(forumId).getName()));
Acá no hace falta hacer el `getForumEntityById` de nuevo solo para sacar el nombre. Mejor hacer `forum.getName()` y ahorrar la consulta a la db.

2023-09-17 13:20 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/service/impl/ForumServiceImpl.java
> +            throw new AlreadyAssignedException("La etiqueta %s ya fue asignada al foro %s".formatted(tag.getName(), getForumEntityById(forumId).getName()));
Mismo comentario que el anterior. Hacer `forum.getName()`.

2023-09-17 13:20 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/service/impl/ForumServiceImpl.java
> +        return forumsDtos;
Acá se puede usar ua lambda para no tener que hacer el `for`. Por ej: `return forums.stream().map(forum -> ForumDto.from(forum, false)).toList();`

2023-09-17 13:20 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/service/impl/ForumServiceImpl.java
> +            throw new UserNotAdminException("El usuario no es el administrador del foro %s".formatted(getForumEntityById(forumId).getName()));
`forumToEdit.getName()`

2023-09-17 13:20 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/service/impl/ForumServiceImpl.java
> +    private List<ForumViewDto> allForumsWithMemebers(List<Forum> forums, Long userId) {
Le cambiaría el nombre a este método por algo como `createForumViewDtosWithIsMember` o algo así. Como está ahora si solo lees el nombre parece que te va a devolver los ForumViewDto con una lista de members.

2023-09-17 13:20 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/service/impl/ForumServiceImpl.java
> +    private boolean isMember(Long forumId, Long userId) {
Acá no podas el `forumId`, conviene mandarle directo el `Forum` así ahorramos hacer la búsqueda de nuevo en la db.

2023-09-17 13:20 UTC, TomasBruno1 commented on src/test/java/com/booklink/backend/service/ForumServiceTest.java
> +        assertNotEquals(savedForum , myForum);
Esto por qué cambió a `NotEquals`? No parece ser algo que tenga que ver con el agregado del `isMember` en los Dto.

2023-09-17 13:20 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/service/impl/UserServiceImpl.java
> +
Para este caso lo que se puede hacer es un método con _generics_ para no repetir la lógica del `ForumServiceImpl`. Podemos pasar los dos métodos (`createForumDtosWithIsMember` y `isMember`) a una `ForumDtoFactory` e incluso hacer los dos métodos `static` para no necesitar una instancia de la _factory_. Usaríamos la misma lógica pero el _return type_ va a cambiar según se necesite.

2023-09-17 23:36 UTC, Joafac4 commented on src/test/java/com/booklink/backend/service/ForumServiceTest.java
> +        assertNotEquals(savedForum , myForum);
eso tomi cambio porque yo le puse que cuando se crea un forum que el forumDto que devuelva sea con isMember = true porque el usuario que lo crea es parte de ese foro, pero cuando se hace un getAllForums te devuevle una lista de forumDto todos con isMember false entonces ese campo es distinto

2023-09-18 01:27 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/dto/forum/ForumDtoFactory.java
> +    public static <T> List<T> createForumViewDtoWithIsMember(List<Forum> forums, Long userId, BiFunction<Forum, Boolean, T> builder) {
Si le podes cambiar el nombre a `createForumDtoWithIsMember` o algo así mejor porque al final no es solo para los `ForumViewDto`

2023-09-18 01:27 UTC, TomasBruno1 approved these changes
LGTM

2023-09-18 02:15 UTC, Joafac4 commented on src/main/java/com/booklink/backend/dto/forum/ForumDtoFactory.java
> +    public static <T> List<T> createForumViewDtoWithIsMember(List<Forum> forums, Long userId, BiFunction<Forum, Boolean, T> builder) {
dale tomi ahi lo cambio

2023-09-18 02:22 UTC, merged