[BOO-196] Validar imagen foro
BookLinkLab/booklink-back pull request #35
Opened 2023-09-21 13:08 UTC by JuanSeZ

https://linear.app/booklink/issue/BOO-196/validar-imagen-foro

2023-09-21 14:05 UTC, Nico-Werner requested changes
Agregale a los tests imagenes .jpg

Y tambien que en la clase que inicializamos la DB ya sean imagenes validas, asi evitamos problemas a futuro

2023-09-25 12:27 UTC, tomasberretta requested changes
Fijate de poner fotos relacionadas a libros para la demo

2023-09-25 21:01 UTC, tomasberretta approved these changes

2023-09-25 21:59 UTC, Nico-Werner approved these changes

2023-09-25 23:09 UTC, merged