BOO-248 Notificaciones según Configuración
BookLinkLab/booklink-back pull request #80
Opened 2023-10-28 23:23 UTC by Joafac4

2023-10-29 16:07 UTC, TomasBruno1 requested changes

2023-10-29 16:07 UTC, TomasBruno1 commented on src/main/java/com/booklink/backend/service/impl/NotificationServiceImpl.java
> +        return filterActivatedNotifications(notifications,activatedNotifications);
En vez de filtrar las notificaciones hay que directamente no crear la notificación si no está en la lista de `forumId`. Esto como lo hiciste va a hacer que igual se llene la db de notificaciones que el usuario tiene desactivadas, y si después el usuario las vuelve a activar le van a aparecer notificaciones de cuando lo tenía desactivado. Fijate los métodos `createPostNotification` y `createCommentNotification`. Esos son los que no deberían crear la notificación si no las tiene activadas el usuario.

2023-10-29 23:03 UTC, Joafac4 commented on src/main/java/com/booklink/backend/service/impl/NotificationServiceImpl.java
> +        return filterActivatedNotifications(notifications,activatedNotifications);
Tomi habia entendido mal. Claro yo las estaba filtrando en lugar de que se cree solo si esta activada, ahi lo cambio

2023-10-30 00:02 UTC, TomasBruno1 approved these changes
LGTM

2023-10-30 00:05 UTC, merged